const CND={plans:[{name:'CND Secure',min:250,duration:'90 days',risk:'Low–Moderate',target:'6–10%',featured:false},{name:'CND Growth',min:1000,duration:'180 days',risk:'Moderate',target:'12–20%',featured:true},{name:'CND Alpha',min:5000,duration:'12 months',risk:'Moderate–High',target:'20–35%',featured:false},{name:'CND Elite',min:25000,duration:'12 months',risk:'High',target:'30–50%',featured:false},{name:'CND Institutional',min:100000,duration:'12–24 months',risk:'Custom',target:'Custom',featured:false}]};
const $=s=>document.querySelector(s);const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(n)||0);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function seed(){if(!localStorage.cnd_demo)localStorage.cnd_demo=JSON.stringify({users:[{id:1,name:'Demo User',email:'client@cnd.com',password:'password123',balance:5740,invested:5000,status:'Verified',joined:'2026-08-20'}],investments:[{id:1,userId:1,plan:'CND Growth',principal:5000,current:5740,maturity:'2026-11-28',status:'Active',return:'14.8%'}],transactions:[{id:1,userId:1,type:'Deposit',amount:5000,asset:'USDT',status:'Completed',date:'2026-08-20'}],withdrawals:[],tickets:[]})}function db(){seed();return JSON.parse(localStorage.cnd_demo)}function save(x){localStorage.cnd_demo=JSON.stringify(x)}
function showTab(prefix,id){document.querySelectorAll(`[data-${prefix}-tab]`).forEach(x=>x.classList.toggle('active',x.dataset[prefix+'Tab']===id));document.querySelectorAll(`[data-${prefix}-page]`).forEach(x=>x.classList.toggle('active',x.dataset[prefix+'Page']===id))}
function calc(){const a=+$('#calcAmount')?.value||0,r=+$('#calcRate')?.value||0;if($('#calcResult'))$('#calcResult').innerHTML=`<span class="muted">Illustrative target value</span><h3>${money(a*(1+r/100))}</h3><span class="muted">Illustrative gain: <strong>${money(a*r/100)}</strong></span>`}
function login(){const d=db(),email=$('#email').value.trim().toLowerCase(),u=d.users.find(x=>x.email.toLowerCase()===email&&x.password===$('#password').value);if(!u)return alert('Invalid demo credentials.');sessionStorage.cndUser=u.id;location.reload()}
function registerBox(){if($('#register'))$('#register').hidden=false}
function register(){const d=db(),name=$('#rname').value.trim(),email=$('#remail').value.trim().toLowerCase(),password=$('#rpassword').value;if(name.length<2||!email||password.length<6)return alert('Use a name, valid email and password of at least 6 characters.');if(d.users.some(x=>x.email===email))return alert('Email already exists.');d.users.push({id:Date.now(),name,email,password,balance:0,invested:0,status:'Pending',joined:new Date().toISOString().slice(0,10)});save(d);alert('Demo account created. Sign in with your new credentials.');$('#register').hidden=true}
function client(){const d=db(),u=d.users.find(x=>x.id===+sessionStorage.cndUser);if(!u){$('#loginView').style.display='grid';$('#portalView').style.display='none';return}$('#loginView').style.display='none';$('#portalView').style.display='block';$('#userName').textContent=u.name;$('#balance').textContent=money(u.balance);$('#invested').textContent=money(u.invested);const inv=d.investments.filter(x=>x.userId===u.id);$('#invCount').textContent=inv.length;$('#pending').textContent=money(d.withdrawals.filter(x=>x.userId===u.id&&x.status==='Pending').reduce((a,x)=>a+x.amount,0));$('#investments').innerHTML=inv.length?inv.map(x=>`<div class="card plan"><div class="portal-head"><div><span class="badge blue">Active plan</span><h3 style="margin-top:10px">${esc(x.plan)}</h3></div><span class="status ok">${esc(x.status)}</span></div><div class="price">${money(x.current)}</div><p class="muted">Principal ${money(x.principal)} · Maturity ${esc(x.maturity)}</p><div class="progress"><i style="width:72%"></i></div><small class="muted">Illustrative progress · ${esc(x.return)} target performance</small></div>`).join(''):'<div class="card empty">No active investments in this demo account.</div>';$('#history').innerHTML=d.transactions.filter(x=>x.userId===u.id).map(x=>`<tr><td>${esc(x.type)}</td><td>${money(x.amount)}</td><td>${esc(x.asset)}</td><td><span class="status ${x.status==='Completed'?'ok':'pending'}">${esc(x.status)}</span></td><td>${esc(x.date)}</td></tr>`).join('')||'<tr><td colspan="5" class="empty">No transactions.</td></tr>'}
function withdraw(){const d=db(),u=d.users.find(x=>x.id===+sessionStorage.cndUser),amount=+$('#wamount').value,address=$('#waddress').value.trim(),asset=$('#wasset').value;if(!u||amount<50||amount>u.balance||!address)return alert('Enter a valid amount, destination and stay within the demo balance.');u.balance-=amount;const id=Date.now();d.withdrawals.unshift({id,userId:u.id,amount,address,asset,status:'Pending',date:new Date().toISOString().slice(0,10)});d.transactions.unshift({id,userId:u.id,type:'Withdrawal Request',amount,asset,status:'Pending',date:new Date().toISOString().slice(0,10)});save(d);$('#wmsg').textContent='Demo request submitted for administrator review.';client()}
function logout(){sessionStorage.removeItem('cndUser');location.reload()}
function approve(id){const d=db(),w=d.withdrawals.find(x=>x.id===id);if(w){w.status='Approved';const t=d.transactions.find(x=>x.type==='Withdrawal Request'&&x.amount===w.amount&&x.userId===w.userId);if(t)t.status='Completed';}save(d);admin()}
function rejectWithdrawal(id){const d=db(),w=d.withdrawals.find(x=>x.id===id);if(w){w.status='Rejected';const u=d.users.find(x=>x.id===w.userId);if(u)u.balance+=w.amount;const t=d.transactions.find(x=>x.type==='Withdrawal Request'&&x.amount===w.amount&&x.userId===w.userId);if(t)t.status='Rejected';}save(d);admin()}
function admin(){const d=db();if(!$('#aUsers'))return;$('#aUsers').textContent=d.users.length;$('#aInv').textContent=d.investments.length;$('#aPending').textContent=d.withdrawals.filter(x=>x.status==='Pending').length;$('#aAum').textContent=money(d.users.reduce((a,x)=>a+x.balance+x.invested,0));$('#adminUsers').innerHTML=d.users.map(u=>`<tr><td>#${u.id}</td><td><strong>${esc(u.name)}</strong><small class="muted">${esc(u.email)}</small></td><td><span class="status ${u.status==='Verified'?'ok':'pending'}">${esc(u.status)}</span></td><td>${money(u.balance)}</td><td>${money(u.invested)}</td><td>${esc(u.joined)}</td></tr>`).join('');$('#adminWithdrawals').innerHTML=d.withdrawals.map(w=>`<tr><td>#${w.id}</td><td>User #${w.userId}</td><td>${money(w.amount)}</td><td>${esc(w.asset)}</td><td><span class="status ${w.status==='Pending'?'pending':w.status==='Approved'?'ok':'risk'}">${esc(w.status)}</span></td><td>${w.status==='Pending'?`<button class="btn primary" onclick="approve(${w.id})">Approve</button> <button class="btn ghost" onclick="rejectWithdrawal(${w.id})">Reject</button>`:'—'}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">No withdrawal requests.</td></tr>';if($('#adminInvestments'))$('#adminInvestments').innerHTML=d.investments.map(x=>{const u=d.users.find(a=>a.id===x.userId);return `<tr><td>#${x.id}</td><td>${esc(u?.name||'Unknown')}</td><td>${esc(x.plan)}</td><td>${money(x.principal)}</td><td>${money(x.current)}</td><td>${esc(x.maturity)}</td><td><span class="status ok">${esc(x.status)}</span></td></tr>`}).join('');}
function toast(msg){const t=$('#toast');if(!t)return;t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
seed();